// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DynamicSkinBuilder
{
    using RoRSkinBuilder.Data;
    using RoRSkinBuilder;
    using DynamicSkinBuilder;
    using UnityEngine;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class DynamicSkinTemplate : DynamicSkinTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"using BepInEx.Logging;
using RoR2;
using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using RuneFoxMods;
using DynamicSkinBuilder;
using MonoMod.RuntimeDetour;


//NameSpace and SkinName are generated from SkinDef Generator
namespace ");
            
            #line 17 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(info.assetInfo.uccModName));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n  public partial class ");
            
            #line 19 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(info.assetInfo.uccModName));
            
            #line default
            #line hidden
            this.Write("Plugin \r\n  {\r\n    ///////////////////////////////////////////////////////////\r\n  " +
                    "  /// Add Declerations of all Modifications here\r\n");
            
            #line 23 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
  foreach(var skin in info.dynamicSkins) { 
    foreach(var mod in skin.modifications) {
            
            #line default
            #line hidden
            this.Write("    Modification ");
            
            #line 25 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(skin.skinDef.name + mod.prefab.name));
            
            #line default
            #line hidden
            this.Write("Modification;\r\n");
            
            #line 26 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
    } 
   } 
            
            #line default
            #line hidden
            this.Write(@"    ///
    ///////////////////////////////////////////////////////////

    ///////////////////////////////////////////////////////////
    /// Local Declarations
    public static Dictionary<string, SkinDef> SkinDefs = new System.Collections.Generic.Dictionary<string, SkinDef>();
    private static GameObject LastModelObject;

    //private static readonly Dictionary<GameObject, Modification> appliedModificatons = new Dictionary<GameObject, Modification>();
    private static Dictionary<string, SortedList<int, Modification>> ModificationList = new Dictionary<string, SortedList<int, Modification>>();//storage for modifications
    private static Dictionary<GameObject, AppliedModifications> ModifiedObjects = new Dictionary<GameObject, AppliedModifications>();

    //This uses Name of class 
    //private static SkinNamePlugin Instance { get; set; }
    //private static ManualLogSource InstanceLogger => Instance?.Logger;
    /// Local Declarations
    ///////////////////////////////////////////////////////////


    partial void BeforeStart()
    {
      Instance = this;

      //On.RoR2.SkinDef.Apply += SkinDefApply; //Old hook for use w/ mmhook
      new Hook(typeof(SkinDef).GetMethod(nameof(SkinDef.Apply)), (Action<Action<SkinDef, GameObject>, SkinDef, GameObject>) SkinDefApply).Apply();
    }

    partial void AfterStart()
    {
      //////////////////////////////////////////////////
      //Should Load all modifications here
");
            
            #line 59 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
  foreach(var skin in info.dynamicSkins) {
    foreach(var mod in skin.modifications) {
    var rend = DynamicSkinHelpers.GetTopParent(mod.parentBone.transform).GetComponentInChildren<SkinnedMeshRenderer>();
      //ModificationName = new Modification("PrefabName.prefab", "ParentName", "BodyName", "SkinNameToken" false, assetBundle);

            
            #line default
            #line hidden
            this.Write("      ");
            
            #line 64 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(skin.skinDef.name + mod.prefab.name));
            
            #line default
            #line hidden
            this.Write("Modification = new Modification(\"");
            
            #line 64 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mod.prefab.name));
            
            #line default
            #line hidden
            this.Write(".prefab\", \"");
            
            #line 64 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mod.parentBone.name));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 64 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(skin.skinDef.bodyName));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 64 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(skin.skinDef.CreateNameToken(info.modInfo.author)));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 64 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DynamicSkinHelpers.GetBoneIndexInList(mod.dynamicBone.transform, rend)));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 64 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mod.affectsBaseModel?"true":"false"));
            
            #line default
            #line hidden
            this.Write(", assetBundle);\r\n");
            
            #line 65 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
   }
  } 
            
            #line default
            #line hidden
            this.Write("      \r\n");
            
            #line 68 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
  foreach(var skin in info.dynamicSkins) { 
    foreach(var mod in skin.modifications) {
    //ModificationName.dynamicBoneData = null; //get from DB reader

            
            #line default
            #line hidden
            this.Write("      ");
            
            #line 72 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(skin.skinDef.name + mod.prefab.name));
            
            #line default
            #line hidden
            this.Write("Modification.dynamicBoneData = ");
            
            #line 72 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DynamicBoneReader.CreateConstructor(mod.dynamicBone)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 73 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
 }
}
            
            #line default
            #line hidden
            this.Write("\r\n      //add mods to mod list\r\n");
            
            #line 77 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
  foreach(var skin in info.dynamicSkins) { 
            
            #line default
            #line hidden
            this.Write(" \r\n      ModificationList.Add(\"");
            
            #line 78 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(skin.skinDef.CreateNameToken(info.modInfo.author)));
            
            #line default
            #line hidden
            this.Write("\",\r\n        new SortedList<int, Modification>() {\r\n");
            
            #line 80 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
    for(int i = 0; i< skin.modifications.Count; i++) {
      var mod = skin.modifications[i];
      var rend = DynamicSkinHelpers.GetTopParent(mod.parentBone.transform).GetComponentInChildren<SkinnedMeshRenderer>();

      //ModificationList.Add(ModificationName);

            
            #line default
            #line hidden
            this.Write("          {");
            
            #line 86 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DynamicSkinHelpers.GetBoneIndexInList(mod.dynamicBone.transform, rend)));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 86 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(skin.skinDef.name + mod.prefab.name));
            
            #line default
            #line hidden
            this.Write("Modification}");
            
            #line 86 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
if(i < skin.modifications.Count - 1){
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 87 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 88 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n        }\r\n      );\r\n      \r\n");
            
            #line 93 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n      //Should Load all modifications here\r\n      /////////////////////////////" +
                    "/////////////////////\r\n    }\r\n\r\n    //Name for this is generated from the skinDe" +
                    "f generator\r\n");
            
            #line 100 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
 foreach(var skin in info.dynamicSkins) { 
            
            #line default
            #line hidden
            this.Write("    static partial void ");
            
            #line 101 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(skin.skinDef.bodyName.ToUpperCamelCase()));
            
            #line default
            #line hidden
            
            #line 101 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(skin.skinDef.name.ToUpperCamelCase()));
            
            #line default
            #line hidden
            this.Write("SkinAdded (SkinDef skinDef, GameObject bodyPrefab)\r\n    {\r\n      SkinDefs.Add(ski" +
                    "nDef.nameToken, skinDef);\r\n    }\r\n");
            
            #line 105 "C:\Users\kamba\Desktop\ROR2 Modding\MyCustomMods\Other\MyScripts\DynamicSkins\DynamicSkinsScripts\DynamicSkinsBuilder\DynamicSkinBuilder\DynamicSkinBuilder\DynamicSkinTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\r\n\r\n///////////////////////////////////////////////////////////////////////////" +
                    "/\r\n    ////// Local Functions (these should not need to be changed when added to" +
                    " different skins)\r\n    \r\n    //private static void SkinDefApply(On.RoR2.SkinDef." +
                    "orig_Apply orig, SkinDef self, GameObject modelObject) //Old SkinDefApply for us" +
                    "e w/ mmhook\r\n    private static void SkinDefApply(Action<SkinDef, GameObject> or" +
                    "ig, SkinDef self, GameObject modelObject)\r\n    {\r\n      orig(self, modelObject);" +
                    "\r\n\r\n      RemoveInvalidModelObjects();\r\n      \r\n      ModifiedObjects.TryGetValu" +
                    "e(modelObject, out var modificatons);\r\n      \r\n      try\r\n      {\r\n\r\n        //i" +
                    "f we are on another character/skin\r\n        SkinDef test;\r\n        var found = S" +
                    "kinDefs.TryGetValue(self.nameToken, out test);\r\n        if(!found)\r\n        {\r\n " +
                    "         if (modificatons != null)\r\n          {\r\n            ClearSkinModificati" +
                    "ons(LastModelObject, modificatons);\r\n          }\r\n          return;\r\n        }\r\n" +
                    "\r\n        if (modificatons == null)\r\n        {\r\n          //otherwise if are now" +
                    " applying modded skin and no modifcations have been made, then apply modificatio" +
                    "ns\r\n\r\n          //create new Applied Entry and pass into Apply\r\n          Applie" +
                    "dModifications NewMods = new AppliedModifications();\r\n          ModifiedObjects." +
                    "Add(modelObject, NewMods);\r\n          ApplySkinModifications(self, modelObject, " +
                    "NewMods);\r\n        }\r\n      }\r\n      catch (Exception e)\r\n      {\r\n        //err" +
                    "or logging may need to be skin specific\r\n        InstanceLogger.LogWarning(\"An e" +
                    "rror occured while adding accessories to a skin\");\r\n        InstanceLogger.LogEr" +
                    "ror(e);\r\n      }\r\n\r\n      //print heiarchy\r\n      //Utils.readheiarchy(modelObje" +
                    "ct);\r\n    }\r\n\r\n    private static void RemoveInvalidModelObjects()\r\n    {\r\n     " +
                    " foreach (var modelObject in ModifiedObjects.Keys.Where(el => !el).ToList())\r\n  " +
                    "    {\r\n        ModifiedObjects.Remove(modelObject);\r\n      }\r\n    }\r\n\r\n    priva" +
                    "te static void ClearSkinModifications(GameObject modelObject, AppliedModificatio" +
                    "ns modifications)\r\n    {\r\n      //NOTE: modifications that modify the base bone " +
                    "list need to have their bones removed first before destruction\r\n      //Modifica" +
                    "tions that modify the base bone list have to be removed in reverse order in orde" +
                    "r to maintain correct indexing\r\n\r\n      //Clear Mods that modify base bone list," +
                    " these need to be done in reverse order\r\n      while (modifications.BaseModelMod" +
                    "ifications.Count != 0)\r\n      {\r\n        var mod = modifications.BaseModelModifi" +
                    "cations.Pop();\r\n\r\n        clearModification(mod, modelObject, modifications);\r\n " +
                    "     }\r\n\r\n      //clear rest of mods\r\n      while (modifications.OtherModificati" +
                    "ons.Count != 0)\r\n      {\r\n        clearModification(modifications.OtherModificat" +
                    "ions[0], modelObject, modifications); //clearmodification calls remove on applie" +
                    "d Mod.\r\n      }\r\n    \r\n      //remove the object from modified once all mods are" +
                    " cleared\r\n      ModifiedObjects.Remove(modelObject);\r\n    }\r\n\r\n    private stati" +
                    "c void ApplySkinModifications(SkinDef skindef, GameObject modelObject, AppliedMo" +
                    "difications modifications)\r\n    {\r\n      var characterModel = modelObject.GetCom" +
                    "ponent<CharacterModel>();\r\n\r\n      LastModelObject = modelObject;\r\n      SortedL" +
                    "ist<int, Modification> modlist;\r\n      if (ModificationList.TryGetValue(skindef." +
                    "nameToken, out modlist))\r\n      {\r\n        foreach (var mod in modlist)\r\n       " +
                    " {\r\n          ApplyModification(modelObject, characterModel, mod.Value, modifica" +
                    "tions);\r\n        }\r\n      }\r\n    }\r\n\r\n    /// <summary>\r\n    /// \r\n    /// </sum" +
                    "mary>\r\n    /// <param name=\"modelObject\">GameObject of ModelObject</param>\r\n    " +
                    "/// <param name=\"modifications\">List for Storing Modifctions</param>\r\n    /// <p" +
                    "aram name=\"characterModel\">Character Model of ModelObject</param>\r\n    /// <para" +
                    "m name=\"modification\">Modification to be apllied</param>\r\n    private static voi" +
                    "d ApplyModification(GameObject modelObject, CharacterModel characterModel, Modif" +
                    "ication modification, AppliedModifications modifications)\r\n    {\r\n      //Get ar" +
                    "amture bone that new prefab will be parented to\r\n      var bodyname = modificati" +
                    "on.bodyname;\r\n      var parentname = modification.parentname;\r\n\r\n      var paren" +
                    "tBone = Utils.FindChildInTree(modelObject.transform, parentname);\r\n      //var p" +
                    "arentBone = modelObject.transform.Find(ChildHelper.GetPath(bodyname, parentname)" +
                    ");\r\n\r\n      GameObject newPart;\r\n\r\n      //we have to instantiate the prefabs in" +
                    " two different ways based on if they affect the model or not\r\n      if (modifica" +
                    "tion.affectsbasemodel)\r\n      {\r\n        //instantiate the model\r\n        newPar" +
                    "t = GameObject.Instantiate(modification.prefab, parentBone, false);\r\n        new" +
                    "Part.name = Utils.RemoveCloneNaming(newPart.name);\r\n        modification.instanc" +
                    "e = newPart;\r\n        modification.inst_armature = newPart; //the armature of th" +
                    "e modifications that affect the base mode is the whole prefab\r\n\r\n        ///////" +
                    "////////////////////////////////////////////////////\r\n        /// Add Bones to B" +
                    "ase Armature here\r\n        var skinRenderers = DynamicSkinHelpers.GetBaseSkinRen" +
                    "derers(modelObject);\r\n\r\n        var newBones = skinRenderers[0].bones.ToList();/" +
                    "/assumption is that we find a skinrenderer here, if not then whoops\r\n\r\n        /" +
                    "/var newBoneIndex = DynamicSkinHelpers.FindBoneIndex2(parentBone, newBones);\r\n  " +
                    "      //insert new bones into array at end of array\r\n        var modBoneArray = " +
                    "DynamicSkinHelpers.BoneArrayBuilder(modification.instance.transform);\r\n        n" +
                    "ewBones.InsertRange(modification.boneIndex, modBoneArray);\r\n\r\n        //add inde" +
                    "x and bonecount to modification\r\n        //modification.boneIndex = newBoneIndex" +
                    ";\r\n        modification.boneCount = modBoneArray.Length;\r\n\r\n        //assign bon" +
                    "es to skin renderers\r\n        foreach (var renderer in skinRenderers)\r\n        {" +
                    "\r\n          renderer.bones = newBones.ToArray();\r\n        }\r\n\r\n        modificat" +
                    "ions.BaseModelModifications.Push(modification);\r\n        /// Add Bones to Base A" +
                    "rmature here\r\n        //////////////////////////////////////////////////////////" +
                    "/\r\n      }\r\n      else\r\n      {\r\n        //instantiate it w/ model as parent\r\n  " +
                    "      newPart = GameObject.Instantiate(modification.prefab, modelObject.transfor" +
                    "m, false);\r\n        newPart.name = Utils.RemoveCloneNaming(newPart.name);\r\n     " +
                    "   modification.instance = newPart;\r\n\r\n        var armature = DynamicSkinHelpers" +
                    ".GetArmature(newPart);\r\n\r\n        //if (armature == null)\r\n        //  Debug.Log" +
                    "(\"Armature not found\");\r\n        //else\r\n        //  Debug.Log(\"armature found: " +
                    "\" + armature.name);\r\n\r\n        //then parent the armature to the parentboned\r\n  " +
                    "      armature.transform.SetParent(parentBone, false);\r\n        modification.ins" +
                    "t_armature = armature.gameObject;\r\n      }\r\n      modification.instance = newPar" +
                    "t;\r\n\r\n      //TODO: add a way to load multiple DynamicBone Scripts for a single " +
                    "modification\r\n    \r\n      //////////////////////////////////////////////////////" +
                    "/////\r\n      /// Add dynamic bones stuff here\r\n      /// Things like DynamicBone" +
                    "s Component, assigning values to dynamic bones component, adding DB_Colliders an" +
                    "d editing them, etc.\r\n      if(modification.dynamicBoneData != null)\r\n      {\r\n " +
                    "     \r\n\r\n        //======================================\r\n        //Add Dynamic" +
                    " Bone Component\r\n        DynamicBone DB = modification.instance.AddComponent<Dyn" +
                    "amicBone>();\r\n        modification.inst_dynamicBone = DB;\r\n\r\n        //=========" +
                    "=============================\r\n        /// Add DynamicBones Colliders to other a" +
                    "rmature bones (Need to do this before Modifying Dynamic Bones component as we ad" +
                    "d them to the DB list during modification)\r\n        List<DynamicBoneCollider> bo" +
                    "nelist = new List<DynamicBoneCollider>();\r\n\r\n        foreach (var colliderData i" +
                    "n modification.dynamicBoneData.m_Colliders)\r\n        {\r\n          var parent = U" +
                    "tils.FindChildInTree(modelObject.transform, colliderData.m_parent_name);\r\n      " +
                    "    //var parent = modelObject.transform.Find(ChildHelper.GetPath(bodyname, coll" +
                    "iderData.m_parent_name));\r\n          \r\n          var bonecollider = parent.gameO" +
                    "bject.AddComponent<DynamicBoneCollider>();\r\n\r\n          bonecollider.m_Direction" +
                    " = colliderData.m_Direction;\r\n          bonecollider.m_Center = colliderData.m_C" +
                    "enter;\r\n          bonecollider.m_Bound = colliderData.m_Bound;\r\n          boneco" +
                    "llider.m_Radius = colliderData.m_Radius;\r\n          bonecollider.m_Height = coll" +
                    "iderData.m_Height;\r\n\r\n          bonelist.Add(bonecollider);\r\n        }\r\n\r\n      " +
                    "  modification.inst_DB_colliders = bonelist;\r\n\r\n        //======================" +
                    "================\r\n        // Modify DynamicBones Component with data\r\n\r\n        " +
                    "var root = Utils.FindChildInTree(modification.inst_armature.transform, modificat" +
                    "ion.dynamicBoneData.m_Root);\r\n\r\n        DB.m_Root = root;\r\n        DB.m_Damping " +
                    "= modification.dynamicBoneData.m_Damping;\r\n        DB.m_DampingDistrib = modific" +
                    "ation.dynamicBoneData.m_DampingDistrib;\r\n        DB.m_Elasticity = modification." +
                    "dynamicBoneData.m_Elasticity;\r\n        DB.m_ElasticityDistrib = modification.dyn" +
                    "amicBoneData.m_ElasticityDistrib;\r\n        DB.m_Stiffness = modification.dynamic" +
                    "BoneData.m_Stiffness;\r\n        DB.m_StiffnessDistrib = modification.dynamicBoneD" +
                    "ata.m_StiffnessDistrib;\r\n        DB.m_Inert = modification.dynamicBoneData.m_Ine" +
                    "rt;\r\n        DB.m_InertDistrib = modification.dynamicBoneData.m_InertDistrib;\r\n " +
                    "       DB.m_Radius = modification.dynamicBoneData.m_Radius;\r\n        DB.m_Radius" +
                    "Distrib = modification.dynamicBoneData.m_RadiusDistrib;\r\n        DB.m_EndLength " +
                    "= modification.dynamicBoneData.m_EndLength;\r\n        DB.m_EndOffset = modificati" +
                    "on.dynamicBoneData.m_EndOffset;\r\n        DB.m_Gravity = modification.dynamicBone" +
                    "Data.m_Gravity;\r\n        DB.m_Force = modification.dynamicBoneData.m_Force;\r\n\r\n " +
                    "       DB.m_Colliders = bonelist;\r\n        DB.m_Exclusions = new List<Transform>" +
                    "();\r\n        foreach (var exclude in modification.dynamicBoneData.m_Exclusions)\r" +
                    "\n        {\r\n          //NOTE: Assumption here is that the dynamic bone root is p" +
                    "art of the new armature and we are only excluding bones located in root\r\n       " +
                    "   var transform = Utils.FindChildInTree(root, exclude);\r\n\r\n          if (transf" +
                    "orm != null)\r\n            DB.m_Exclusions.Add(transform);\r\n          else\r\n     " +
                    "       Debug.LogWarning(\"Tried to exclude a transform that could not be found\");" +
                    "\r\n        }\r\n\r\n\r\n        DB.m_FreezeAxis = modification.dynamicBoneData.m_Freeze" +
                    "Axis;\r\n\r\n        //TODO: Read DB and compare it to what\'s made in OG mod cause s" +
                    "kirt is behaving oddly\r\n    \r\n      }\r\n      /// Add dynamic bones stuff here\r\n " +
                    "     ///////////////////////////////////////////////////////////\r\n\r\n      //////" +
                    "/////////////////////////////////////////////////////\r\n      /// Add renderers t" +
                    "o the character\'s renderer list\r\n\r\n      //get renderers\r\n      var renderers = " +
                    "newPart.GetComponentsInChildren<SkinnedMeshRenderer>(true);\r\n\r\n      //resize re" +
                    "nder array to account for new renderers\r\n      Array.Resize(ref characterModel.b" +
                    "aseRendererInfos, characterModel.baseRendererInfos.Length + renderers.Length);\r\n" +
                    "\r\n      //NOTE: Need to save the number of renderers added to the character rend" +
                    "er info so we can remove them cleanly. Probably add this to modifications\r\n     " +
                    " if (renderers.Length != 0)\r\n      {\r\n        int i = renderers.Length;\r\n       " +
                    " foreach (var renderer in renderers)\r\n        {\r\n          //2 to add - 3 in\r\n  " +
                    "        //resize array to 5\r\n          //first is added at 5-2 (3) which is posi" +
                    "tion 4\r\n          //second is added at 5-1 (4) which is position 5\r\n          //" +
                    "exits\r\n\r\n          characterModel.baseRendererInfos[characterModel.baseRendererI" +
                    "nfos.Length - i] = new CharacterModel.RendererInfo\r\n          {\r\n            ren" +
                    "derer = renderers[renderers.Length - i],\r\n            ignoreOverlays = false,\r\n " +
                    "           defaultShadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.On" +
                    ",\r\n            defaultMaterial = renderer.sharedMaterial\r\n          };\r\n\r\n      " +
                    "    i--; //decrement i to reach the next renederer\r\n        }\r\n      }\r\n      //" +
                    "/ Add renderers to the character\'s renderer list\r\n      ////////////////////////" +
                    "///////////////////////////////////\r\n\r\n      //Push to applied modifications whe" +
                    "n done\r\n      modifications.OtherModifications.Add(modification);\r\n    }\r\n\r\n    " +
                    "private static void clearModification(Modification modification, GameObject mode" +
                    "lObject, AppliedModifications modifications)\r\n    {\r\n      //Destroy Dynamic Bon" +
                    "es colliders\r\n      if(modification.inst_DB_colliders != null)\r\n      {     \r\n  " +
                    "      foreach (var collider in modification.inst_DB_colliders)\r\n        {\r\n     " +
                    "     Destroy(collider);\r\n        }\r\n      }\r\n\r\n      //Remove Additions to Bone " +
                    "Arrays\r\n      if (modification.affectsbasemodel)\r\n      {\r\n        var renderers" +
                    " = DynamicSkinHelpers.GetBaseSkinRenderers(modelObject);\r\n        var oldBones =" +
                    " renderers[0].bones.ToList();\r\n\r\n        oldBones.RemoveRange(modification.boneI" +
                    "ndex, modification.boneCount);\r\n\r\n        foreach (var renderer in renderers)\r\n " +
                    "       {\r\n          renderer.bones = oldBones.ToArray();\r\n        }\r\n      }\r\n\r\n" +
                    "      //Destroy Dynamic Bones Component (Probably don\'t have to do this since it" +
                    " will be destroyed along with PrefabInstance if parented to it)\r\n      Destroy(m" +
                    "odifications.OtherModifications[0].inst_dynamicBone);\r\n      //Destroy Armature\r" +
                    "\n      Destroy(modifications.OtherModifications[0].inst_armature);\r\n      //Dest" +
                    "roy Prefab Instance\r\n      Destroy(modifications.OtherModifications[0].instance)" +
                    ";\r\n\r\n      bool removed = modifications.OtherModifications.Remove(modification);" +
                    "\r\n      if (!removed) InstanceLogger.LogError(\"Skin Modification was not removed" +
                    "\");\r\n    }\r\n\r\n    ////// Local Functions\r\n    //////////////////////////////////" +
                    "//////////////////////////////////////////\r\n\r\n    //////////////////////////////" +
                    "//////////////////////////////////////////////\r\n    ////// Local Classes\r\n    cl" +
                    "ass Modification\r\n    {\r\n\r\n      public Modification(string PrefabPath, string P" +
                    "arentName, string BodyName, string ParentSkinToken, int BoneIndex, bool AffectsB" +
                    "aseModel, AssetBundle assetBundle)\r\n      {\r\n        bodyname = BodyName;\r\n     " +
                    "   prefabpath = PrefabPath;\r\n        parentname = ParentName;\r\n        parentSki" +
                    "nToken = ParentSkinToken;\r\n        affectsbasemodel = AffectsBaseModel;\r\n       " +
                    " boneIndex = BoneIndex;\r\n        prefab = assetBundle.LoadAsset<GameObject>(@pre" +
                    "fabpath);\r\n        if (prefab == null) { Debug.LogWarning(\"Asset at \" + PrefabPa" +
                    "th + \" was not loaded\"); } //DEBUG check for if asset was not loaded\r\n      }\r\n\r" +
                    "\n      //////////////////////////////////////////////////////\r\n      /// These a" +
                    "re created when the Modification is created\r\n      public string prefabpath;\r\n  " +
                    "    public string bodyname; //Name of the base BodyName. i.e. MercBody or MageBo" +
                    "dy\r\n      public string parentname; //the name of the bone we want to parent thi" +
                    "s modification to\r\n      public GameObject prefab;\r\n      public bool affectsbas" +
                    "emodel; //if the modification affects the base model then we need to do addition" +
                    "al steps\r\n      //TODO: Add Support for multiple Dynamic Bone Scripts per modifi" +
                    "cation\r\n      public DynamicBoneData dynamicBoneData;\r\n      public string paren" +
                    "tSkinToken;\r\n      /// \r\n      /////////////////////////////////////////////////" +
                    "/////\r\n\r\n      //////////////////////////////////////////////////////\r\n      ///" +
                    " Used for bones that need to be added to base model\r\n      public int boneIndex;" +
                    " //index of bone in bone array, created on modification\r\n      public int boneCo" +
                    "unt; //number of bones in prefab bone armature\r\n                            ///\r" +
                    "\n      //////////////////////////////////////////////////////\r\n\r\n      /////////" +
                    "/////////////////////////////////////////////\r\n      /// These objects are insta" +
                    "nceated and destroyed on skinDefApply\r\n      public GameObject instance; //The c" +
                    "reated instance of the prefab attatched to the character\r\n      public GameObjec" +
                    "t inst_armature; //the armature of the created instance\r\n    \r\n    //TODO: add s" +
                    "upport for multiple DynamicBone Scripts per modification\r\n      public DynamicBo" +
                    "ne inst_dynamicBone; //the dynamic bone attatched to the instance\r\n      public " +
                    "List<DynamicBoneCollider> inst_DB_colliders = new List<DynamicBoneCollider>(); /" +
                    "/List of Dynamic Bone Colliders that were attatched to other bones for this modi" +
                    "fication\r\n                                                                      " +
                    "                   ///\r\n      //////////////////////////////////////////////////" +
                    "////\r\n\r\n      //This only contained the Skinned Mesh Renderers and I think I can" +
                    " do these inline instead\r\n      // /////////////////////////////////////////////" +
                    "/////////\r\n      // /// These don\'t seem to be created or destroyed and are just" +
                    " assigned to\r\n      // \r\n      // //Note: it looks like all the mesh renderers a" +
                    "re using the same bone list as the base code only ever looked at the one and ass" +
                    "igned to both\r\n      // //these were taken from the meshes at root of the model\r" +
                    "\n      // SkinnedMeshRenderer[] meshRenderers;\r\n      // \r\n      // /// These do" +
                    "n\'t seem to be created or destroyed and are just assigned to\r\n      // /////////" +
                    "/////////////////////////////////////////////\r\n    }\r\n\r\n    class AppliedModific" +
                    "ations\r\n    {\r\n      public Stack<Modification> BaseModelModifications = new Sta" +
                    "ck<Modification>();\r\n      public List<Modification> OtherModifications = new Li" +
                    "st<Modification>();//storage for modifications\r\n    }\r\n\r\n\r\n    //Data classes in" +
                    "clude strings in place of transforms as we need to search for the transforms whe" +
                    "n we load the data in\r\n    class DynamicBoneData\r\n    {\r\n      public DynamicBon" +
                    "eData(string root,\r\n                     float damping, AnimationCurve damping_d" +
                    "ist,\r\n                     float elasticity, AnimationCurve elasticity_dist,\r\n  " +
                    "                   float stiffness, AnimationCurve stiffness_dist,\r\n            " +
                    "         float inert, AnimationCurve inert_dist,\r\n                     //float f" +
                    "riction, AnimationCurve friction_dist, //NOTE: looks like ROR2 is using an older" +
                    " version of DynBone that doesn\'t have friction\r\n                     float radiu" +
                    "s, AnimationCurve radius_dist,\r\n                     float end_length, Vector3 e" +
                    "nd_offset,\r\n                     Vector3 gravity, Vector3 force,\r\n              " +
                    "       List<DynamicBoneColliderData> colliders,\r\n                     List<strin" +
                    "g> exclusions,\r\n                     DynamicBone.FreezeAxis freeze_axis)\r\n      " +
                    "{\r\n        m_Root = root;\r\n        m_Damping = damping;\r\n        m_DampingDistri" +
                    "b = damping_dist;\r\n        m_Elasticity = elasticity;\r\n        m_ElasticityDistr" +
                    "ib = elasticity_dist;\r\n        m_Stiffness = stiffness;\r\n        m_StiffnessDist" +
                    "rib = stiffness_dist;\r\n        m_Inert = inert;\r\n        m_InertDistrib = inert_" +
                    "dist;\r\n        //new_DB.m_Friction = friction;\r\n        //new_DB.m_FrictionDistr" +
                    "ib = friction_dist;\r\n        m_Radius = radius;\r\n        m_RadiusDistrib = radiu" +
                    "s_dist;\r\n        m_EndLength = end_length;\r\n        m_EndOffset = end_offset;\r\n " +
                    "       m_Gravity = gravity;\r\n        m_Force = force;\r\n        m_Colliders = col" +
                    "liders;\r\n        m_Exclusions = exclusions;\r\n        m_FreezeAxis = freeze_axis;" +
                    "\r\n      }\r\n    \r\n      //would include string for parent_name but all dynamicbon" +
                    "es should be created on modification_instance\r\n\r\n      public string m_Root;\r\n  " +
                    "    public float m_Damping;\r\n      public AnimationCurve m_DampingDistrib;\r\n    " +
                    "  public float m_Elasticity;\r\n      public AnimationCurve m_ElasticityDistrib;\r\n" +
                    "      public float m_Stiffness;\r\n      public AnimationCurve m_StiffnessDistrib;" +
                    "\r\n      public float m_Inert;\r\n      public AnimationCurve m_InertDistrib;\r\n    " +
                    "  //public float friction; public AnimationCurve friction_dist; //NOTE: looks li" +
                    "ke ROR2 is using an older version of DynBone that doesn\'t have friction\r\n      p" +
                    "ublic float m_Radius;\r\n      public AnimationCurve m_RadiusDistrib;\r\n      publi" +
                    "c float m_EndLength;\r\n      public Vector3 m_EndOffset;\r\n      public Vector3 m_" +
                    "Gravity;\r\n      public Vector3 m_Force;\r\n      public List<DynamicBoneColliderDa" +
                    "ta> m_Colliders;\r\n      public List<string> m_Exclusions;\r\n      public DynamicB" +
                    "one.FreezeAxis m_FreezeAxis;\r\n    }\r\n\r\n    class DynamicBoneColliderData\r\n    {\r" +
                    "\n      public DynamicBoneColliderData(string parent_name, DynamicBoneCollider.Di" +
                    "rection direction, Vector3 Center, DynamicBoneCollider.Bound bound, float radius" +
                    ", float heaight)\r\n      {\r\n        m_parent_name = parent_name;\r\n        m_Direc" +
                    "tion = direction;\r\n        m_Center = Center;\r\n        m_Bound = bound;\r\n       " +
                    " m_Radius = radius;\r\n        m_Height = heaight;\r\n      }\r\n\r\n      public string" +
                    " m_parent_name;\r\n      public DynamicBoneCollider.Direction m_Direction;\r\n      " +
                    "public Vector3 m_Center;\r\n      public DynamicBoneCollider.Bound m_Bound;\r\n     " +
                    " public float m_Radius;\r\n      public float m_Height;\r\n\r\n    }\r\n\r\n    ////// Loc" +
                    "al Classes\r\n    ////////////////////////////////////////////////////////////////" +
                    "////////////\r\n  }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class DynamicSkinTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
